language: objective-c
osx_image: xcode7.2
before_script:
  - cp soundcloudql-swift/Api/Environment.plist.sample soundcloudql-swift/Api/Environment.plist
install:
  - gem install bundler
  - bundle install
script:
  - bundle exec fastlane test
